<?php
/**
 * @param
 *   $type string - the Service to call. Valid $types:
 *     - 'GetDetectScript'
 *     - 'GetInstallScript'
 * @return
 *   array - JS Code (string) and HTML (string)
 *
 * This function will attempt to return results from the local cache before
 * making a call to the API.
 */
function clipapicache_getscript($type = 'GetDetectScript') {
  $cid = 'clipapi_GetDetectJs-' . $type . $_SERVER['HTTP_USER_AGENT'];
  $data = cache_get($cid);
  if (empty($data)) {
    $gds = clipapi_get($type);
    $data = array(
      'JSCode' => $gds['JSCode'],
      'HTML' => $gds['HTML'],
    );
    $table = 'cache';
    $expire = (time() + (60*60*24*7));
    cache_set($cid, $data, $table, $expire);
  }
  else {
    $gds = $data->data;
  }
  return $gds;
}
