<?php

/**
 * Implementation of hook_block to create the "Selected Offers" block for the right sidebar
 *
 * Also using this module to create a block for the header that contains the total coupons on the site
 */
function clipapiprint_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == "list") {
    // Generate listing of blocks from this module, for the admin/block page
    $block = array();

    $block['selected-offers'] = array(
      'info' => t('Selected Offers'),
      'status' => 1,
      'weight' => 1,
      'region' => 'right',
    );

    $block['total-savings'] = array(
      'info' => t('Total Savings'),
      'status' => 1,
      'weight' => 1,
      'region' => 'header',
    );

    return $block;
  }// END "list"

  elseif ($op == "view") {
    //Add the JS file
    drupal_add_js(drupal_get_path('module', 'clipapiprint') . '/includes/jquery-1.7.2.min.js', 'core');
    drupal_add_js(drupal_get_path('module', 'clipapiprint') . '/includes/jquery.cookie.js');
    drupal_add_js(drupal_get_path('module', 'clipapiprint') . '/includes/fancybox/jquery.fancybox-1.3.4.pack.js');
    drupal_add_js(drupal_get_path('module', 'clipapiprint') . '/includes/offer-select.js');
    drupal_add_css(drupal_get_path('module', 'clipapiprint') . '/includes/fancybox/jquery.fancybox-1.3.4.css');

    // Add Coupons Inc Detect and Install JS
    $script = clipapicache_getscript('GetDetectScript');
    drupal_add_js(strip_tags($script['JSCode']), 'inline');
    $script = clipapicache_getscript('GetInstallScript');
    drupal_add_js(strip_tags($script['JSCode']), 'inline');

    // Generate block content
    // content variable that will be returned for display
     switch ($delta) {
       case 'selected-offers':
         $site_instance = explode('/',  request_uri());
         $site_instance = check_plain($site_instance[1]);
         $microsite_vars = variable_get('site-manager-' . $site_instance, '');

         $block_subject = 'Selected Coupons';
         $block_content = "<div id='selected-offers'></div>
                           <div class='clear'></div>
                           <div id='savings' class='lucida'>
                             <div id='coupon-count'>
                               <em>My</em> Coupons: <span class='dyn'>0</span>
                             </div>
                             <div id='savings-amount'>
                               <em>My</em> Savings: <span>$</span><span class='dyn'>0.00</span>
                             </div>
                           </div>
                           <a class='print-link background-color1' href='#'>Print My Coupons</a>
                           <div id='PrintToken'></div>
                           <a href='http://coupons.com' class='iframe' id='ccprint'>Print Now</a>
                          ";
       break;
     }

     switch ($delta) {
       case 'total-savings':
         $block_subject = '';
         $count = 0;
         $total = 0;
         $result = db_query("SELECT {content_type_offer.field_amount_value} FROM {content_type_offer} LEFT JOIN {content_field_sites} ON {content_field_sites.nid}={content_type_offer.nid} WHERE {content_field_sites.field_sites_value} = 'bfy'");
         while ($row = db_fetch_array($result)) {
           $count++;
           $total = ($total + $row['field_amount_value']);
         }
         variable_set('coupon_count', $count);
         $total = number_format($total, 2);
         $total = explode('.', $total);
         $block_content = '<div class="todays-coupons-count lucida">
                             <div class="title">Today\'s Coupons</div>
                             <div class="value">' . $count . '</div>
                           </div>
                           <div class="total-savings-count lucida">
                             <div class="title">Total Savings</div>
                             <div class="value">' . $total[0] . '<span>.' . $total[1] . '</span></div>
                           </div>
                          ';
       break;
     }

    // set up the block
    $block = array();
    $block['subject'] = $block_subject;
    $block['content'] = $block_content;
    return $block;

  }// END "view"
}

//Create the savings page
//The content for this page is generated in savings.inc
function clipapiprint_menu() {

  $items = array($form_state);

  $items['savings'] = array(
    'title' => t('Calculated Savings'),
    'page callback' => 'savings',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'savings.inc',
  );

  $items['clipapiprint/%/%'] = array(
    'title' => t('CLIP API Print API'),
    'page callback' => 'clipapiprintapi',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'clipapiprintapi.inc',
  );

  return $items;
}

